net/bpf: Change "min_tso_segs" tcp congestion op to "tso_segs"
Since 4ee004a30d45cec170d7c5d176068a9a2885d0bb, we get build error
below:

net/ipv4/bpf_tcp_ca.c:19:38: error: ‘struct tcp_congestion_ops’ has no member named ‘min_tso_segs’; did you mean ‘tso_segs’?
   19 |  offsetof(struct tcp_congestion_ops, min_tso_segs),
      |                                      ^~~~~~~~~~~~
././include/linux/compiler_types.h:135:57: note: in definition of macro ‘__compiler_offsetof’
  135 | #define __compiler_offsetof(a, b) __builtin_offsetof(a, b)
      |                                                         ^
net/ipv4/bpf_tcp_ca.c:19:2: note: in expansion of macro ‘offsetof’
   19 |  offsetof(struct tcp_congestion_ops, min_tso_segs),
      |  ^~~~~~~~

Changing the affected line to the new option fixes the build.