Revert "drm/msm/sde: allocate kmem_fence_pool once"
fixes error:
ld.lld: error: duplicate symbol: __initstub__kmod_msm_drm
>>> defined in techpack/built-in.a(display/msm/sde/sde_fence.o)
>>> defined in techpack/built-in.a(display/msm/msm_drv.o)
make[1]: *** [/home/danya2271/android_kernel_oneplus_sm8450/Makefile:1514: vmlinux] Error 1

This reverts commit 6f56d34494fe358a29ab167571cf7044b8883cbf.